---

- name: Configure hub.conf
  template:
    src: hub.conf.j2
    dest: /etc/koji-hub/hub.conf
    owner: root
    group: root
    mode: '0640'
  tags:
    - hub
    - koji-hub-conf
    - koji-hub-config

- include: configure_apache.yml
  tags: koji-apache-conf

- name: Make kojiDir directory
  file:
    path: "{{ koji_hub_KojiDir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - hub
    - dirs

- name: Make directory tree for koji in kojiDir
  file:
    path: "{{ koji_hub_KojiDir }}/{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - packages
    - repos
    - work
    - scratch
  tags:
    - hub
    - dirs

- name: issue cert for koji-hub
  shell: "{{ ca_root_path }}/certgen.sh {{ ansible_fqdn }}"
  args:
    creates: "{{ ca_root_path }}/certs/{{ ansible_fqdn }}.crt"
    chdir: "{{ ca_root_path }}"
  when: koji_hub_issue_cert
  tags:
    - hub

- include: selinux.yml
  when: "ansible_selinux.status == 'enabled'"

- name: "Ensure httpd is running"
  service: name=httpd state=started enabled=yes
  tags:
    - hub
    - hub-service
    - koji-apache-conf
    - koji-service

