---

- name: Main | Install {{ koji_hub_package }}
  package:
    name: "{{ koji_hub_package }}"
    state: present

- name: Install | Install deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - httpd
    - mod_ssl
  tags:
    - hub
    - hub-packages

- name: Install | Install additional OS-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ koji_hub_additional_packages }}"
  tags:
    - hub
    - hub-packages
