---

- name: Kojiadmin | Create kojiadmin user
  user: name={{ item }} state=present
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin

- name: Kojiadmin | Create /home/kojiadmin/.koji
  file: path=/home/{{ item }}/.koji state=directory mode=0750
  su: yes
  su_user: "{{ item }}"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin

- name: issue cert for kojiadmin
  shell: "{{ ca_root_path }}/certgen.sh {{ item }}"
  args:
    creates: "{{ ca_root_path }}/certs/{{ item }}.crt"
    chdir: "{{ ca_root_path }}"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin
    - kojiadmin-cert

- name: make p12 cert for kojiadmin for importing to web-browser
  shell: "{{ ca_root_path }}/webcertgen.sh {{ item }}"
  args:
    creates: "{{ ca_root_path }}/webcerts/{{ item }}_browser_cert.p12"
    chdir: "{{ ca_root_path }}"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin
    - kojiadmin-cert
    - kojiadmin-p12

- name: Kojiadmin | Copy kojiadmin pem file to ~/.koji/client.crt
  shell: "cp -p /etc/pki/koji/pems/{{ item }}.pem /home/{{ item }}/.koji/client.crt"
  args:
    creates: "/home/{{ item }}/.koji/client.crt"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin

# TODO debug why this block doesn't work
# - name: Kojiadmin | Copy CA cert to kojiadmin home
#   shell: "cp ${item.0} ${item.1}"
#   with_items:
#     - [ '/etc/pki/koji/koji_ca_cert.crt', '/home/kojiadmin/.koji/clientca.crt' ]
#     - [ '/etc/pki/koji/koji_ca_cert.crt', '/home/kojiadmin/.koji/serverca.crt' ]
#   args:
#     creates: /home/kojiadmin/.koji/clientca.crt
#   tags:
#     - kojiadmin

# But for now
- name: Kojiadmin | Copy CA cert to /home/kojiadmin/.koji/clientca.crt
  shell: "cp /etc/pki/koji/koji_ca_cert.crt /home/{{ item }}/.koji/clientca.crt"
  args:
    creates: "/home/{{ item }}/.koji/clientca.crt"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin

- name: Kojiadmin | Copy CA cert to /home/kojiadmin/.koji/serverca.crt
  shell: "cp /etc/pki/koji/koji_ca_cert.crt /home/{{ item }}/.koji/serverca.crt"
  args:
    creates: "/home/{{ item }}/.koji/serverca.crt"
  with_items: koji_hub_kojiadmins  
  tags:
    - kojiadmin

- name: Kojiadmin | Make tar to send to user
  shell: "tar cvzf /home/{{ item }}/koji-{{ item }}.tag.gz /home/{{ item }}/.koji/client.crt /home/{{ item }}/.koji/clientca.crt /home/{{ item }}/.koji/serverca.crt"
  args:
    creates: "/home/{{ item }}/koji-{{ item }}.tag.gz"
  su: yes
  su_user: "{{ item }}"
  with_items: koji_hub_kojiadmins
  tags:
    - kojiadmin
    - kojiadmin-tar
