---

- name: Kojiadmin | Create kojiadmin user
  user: name={{ item.name }} state=present
  with_items: "{{ koji_hub_kojiadmins }}"
  tags:
    - kojiadmin
    - kojiadmin-user

- name: Kojiadmin | Create /home/kojiadmin/.koji
  file: path=/home/{{ item.name }}/.koji state=directory mode=0750
  become: yes
  become_user: "{{ item.name }}"
  with_items: "{{ koji_hub_kojiadmins }}"
  tags:
    - kojiadmin

- include: kojiadmin_issue_certs.yml
  when: koji_hub_issue_cert_for_kojiadmins
